apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo2
  name: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo2
    spec:
      containers:
      - image: azdraftdemo2cr.azurecr.io/demo2
        name: demo2
        ports:
        - containerPort: 80
        resources: {}
status: {}
